name: flut_micro_commons_dependencies
description: Flutter Commons Dependencies
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.6
  flutter_keyboard_visibility: ^5.2.0
  cloud_firestore: ^2.5.3
  flutter_modular: ^4.0.1
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  google_sign_in: ^5.2.4
  dio: ^4.0.4
  mobx: ^2.0.6+1
  localization: ^1.0.0
  supercharged: ^2.0.0
  enum_to_string: ^2.0.1
  recase: ^4.0.0
  flutter_mobx: ^2.0.2
  mask_text_input_formatter: ^2.0.0
  dartz: ^0.10.0
  asuka: ^2.0.0-nullsafety.2
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  timer_count_down: ^2.2.0
  unicons: ^2.0.1
  carousel_slider: ^4.0.0
  insta_like_button: ^0.1.1
  like_button: ^2.0.3
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.8

dev_dependencies:
  build_runner: ^2.1.1
  modular_codegen: ^3.0.0
  modular_test: ^1.0.1+1
  mobx_codegen: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
